lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 7200
    token_extractors:
        authorization_header:
            enabled: false

        cookie:
            enabled: true

    set_cookies:
        BEARER:
            # lifetime: null (defaults to token ttl)
            samesite: none
            # path: /
            domain: "%env(COOKIE_DOMAIN)%" # null (null means automatically set by symfony)
            # secure: true (default to true)
            # httpOnly: true
